import { execSync } from "child_process";
import crypto from "crypto";
import fs from "fs";
import path from "path";

const rootDir = path.resolve(__dirname, "../../..");
const contractsDir = path.join(rootDir, "contracts");
const wasmPath = path.join(
  contractsDir,
  "target/wasm32-unknown-unknown/release/yield_vault.wasm"
);
const outputDir = path.join(rootDir, "packages/sdk/src/generated");
const outputFile = path.join(outputDir, "yield_vault.ts");
const tempOutputDir = path.join(outputDir, "_temp_bindings");

function main() {
  console.log("--> Building YieldVault WASM artifact...");
  if (!fs.existsSync(wasmPath)) {
    execSync(
      "cargo build -p yield_vault --target wasm32-unknown-unknown --release",
      {
        cwd: contractsDir,
        stdio: "inherit",
      }
    );
  }

  const wasmBuffer = fs.readFileSync(wasmPath);
  const specHash = crypto
    .createHash("sha256")
    .update(wasmBuffer)
    .digest("hex");
  console.log(`--> YieldVault WASM Spec SHA-256: ${specHash}`);

  let cliVersion = "stellar 25.1.0";
  try {
    cliVersion = execSync("stellar --version", { encoding: "utf-8" }).trim().split("\n")[0];
  } catch {
    // fallback
  }

  console.log("--> Generating TypeScript bindings via Stellar CLI...");
  if (fs.existsSync(tempOutputDir)) {
    fs.rmSync(tempOutputDir, { recursive: true, force: true });
  }

  execSync(
    `stellar contract bindings typescript --wasm "${wasmPath}" --output-dir "${tempOutputDir}" --overwrite`,
    { stdio: "inherit" }
  );

  const generatedIndex = path.join(tempOutputDir, "src/index.ts");
  if (!fs.existsSync(generatedIndex)) {
    throw new Error(`Failed to locate generated bindings at ${generatedIndex}`);
  }

  const rawCode = fs.readFileSync(generatedIndex, "utf-8");

  const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
 *
 * Generated by build-bindings script.
 * Tool Version: ${cliVersion}
 * Spec SHA-256 Hash: ${specHash}
 */

export const YIELD_VAULT_SPEC_HASH = "${specHash}";
export const STELLAR_CLI_VERSION = "${cliVersion}";

`;

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(outputFile, header + rawCode);

  fs.rmSync(tempOutputDir, { recursive: true, force: true });

  console.log(`✅ Successfully generated bindings at ${outputFile}`);
}

main();
